# Generated by Django 3.2.13 on 2022-04-28 18:08

import api.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


from django.db import migrations


def apply_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group(name="admin").save()


def revert_migration(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get(name="admin").delete()


class Migration(migrations.Migration):
    operations = [migrations.RunPython(apply_migration, revert_migration)]
