version: "3.7"

services:
  postgres:
    image: your_docker_repo/postgres:13.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app_db:/var/lib/postgresql/data
      - ./init-db-schema.sql:/docker-entrypoint-initdb.d/init-db-schema.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: mvt

volumes:
  app_db:
