"""
Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_api_key",
    "django_filters",
    "api.apps.ApiConfig",
    "elasticapm.contrib.django",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dependencies.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dependencies.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = "/djangostatic/"
STATIC_ROOT = os.path.join(BASE_DIR, "djangostatic")

# Other Django settings
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"  # New in Django 3.2

# Django rest framework
REST_FRAMEWORK = {
    "DATE_INPUT_FORMATS": ["%m/%d/%Y"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

# Custom Application Settings
# Error report filtering
SENSITIVE_VARIABLES = ["password", "credentials"]
DEFAULT_EXCEPTION_REPORTER_FILTER = (
    "dependencies.reporter_filters.RecursiveSafeExceptionReporterFilter"
)

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Required for Django group permissions to work
    "api.authentication.LdapDjangoAuthentication",  # Used by django template pages (like admin/)
]

# LDAP
LDAP_HOST = "ldaps://ad-ldap-prod..com:636"
LDAP_BASE = "dc=ms,dc=ds,dc=,dc=com"
# Group names in the form that LDAP recognizes
LDAP_USER_GROUP = "CN=CnS_Config_Automation,CN=Users,DC=ms,DC=ds,DC=,DC=com"
LDAP_ADMIN_GROUP = "CN=CnS_ConfigAdmin,CN=Users,DC=ms,DC=ds,DC=,DC=com"
# LDAP_CACERTFILE is set in the development and production settings files due to differing paths

# SMTP (Email)
EMAIL_HOST = "ctc-smtp-relay-ose.com"  # SMTP Server
EMAIL_TIMEOUT = 30
